server:
  port: 4141
  host: localhost
  domain: https://tokens.twitchio.dev
  build: "eira/dist/html"
sessions:
  max_age: 604800
valkey:
  db: 0
  port: 6379
database:
  dsn: postgres://USER:PASSWORD@localhost:5432/DATABASE
twitch:
  client_id:
  client_secret: 